/**
 * VJam FX — Preset Catalog
 * All available preset categories and flat list
 */

export const PRESET_CATEGORIES = [
  { label: 'Immersive', presets: [
    { id: 'neon-tunnel', name: 'Neon Tunnel' },
    { id: 'laser-tunnel', name: 'Laser Tunnel' },
    { id: 'infinite-zoom', name: 'Infinite Zoom' },
    { id: 'hypnotic', name: 'Hypnotic' },
    { id: 'wormhole', name: 'Wormhole' },
    { id: 'warp-speed', name: 'Warp Speed' },
    { id: 'tunnel-zoom', name: 'Tunnel Zoom' },
    { id: 'root-tunnel', name: 'Root Tunnel' },
    { id: 'helix-tunnel', name: 'Helix Tunnel' },
    { id: 'deep-dive', name: 'Deep Dive' },
    { id: 'deep-ocean', name: 'Deep Ocean' },
    { id: 'portal-ring', name: 'Portal Ring' },
    { id: 'cyber-corridor', name: 'Cyber Corridor' },
    { id: 'time-warp', name: 'Time Warp' },
    { id: 'gravity-well', name: 'Gravity Well' },
    { id: 'plasma-wave', name: 'Plasma Wave' },
    { id: 'aurora', name: 'Aurora' },
    { id: 'northern-lights', name: 'Northern Lights' },
    { id: 'crystal-cave', name: 'Crystal Cave' },
    { id: 'chrome-wave', name: 'Chrome Wave' },
    { id: 'sunset-drive', name: 'Sunset Drive' },
    { id: 'neon-highway', name: 'Neon Highway' },
    { id: 'dna-aurora', name: 'DNA Aurora' },
    { id: 'plasma-ball', name: 'Plasma Ball' },
    { id: 'hologram', name: 'Hologram' },
  ]},
  { label: 'Frames & Film', presets: [
    { id: 'neon-frame', name: 'Neon Frame' },
    { id: 'light-leak', name: 'Light Leak' },
    { id: 'film-burn', name: 'Film Burn' },
    { id: 'film-scratch', name: 'Film Scratch' },
    { id: 'scan-line', name: 'Scan Line' },
    { id: 'vhs-noise', name: 'VHS Noise' },
    { id: 'vhs-tracking', name: 'VHS Tracking' },
    { id: 'film-grain', name: 'Film Grain' },
    { id: 'film-countdown', name: 'Film Countdown' },
    { id: 'film-reel', name: 'Film Reel' },
    { id: 'vhs-rewind', name: 'VHS Rewind' },
    { id: 'polaroid-flash', name: 'Polaroid Flash' },
    { id: 'tape-distort', name: 'Tape Distort' },
  ]},
  { label: 'Patterns', presets: [
    { id: 'kaleidoscope', name: 'Kaleidoscope' },
    { id: 'mandala', name: 'Mandala' },
    { id: 'sacred-geometry', name: 'Sacred Geometry' },
    { id: 'moire', name: 'Moire' },
    { id: 'prism', name: 'Prism' },
    { id: 'barcode', name: 'Barcode' },
    { id: 'spirograph', name: 'Spirograph' },
    { id: 'cyber-mandala', name: 'Cyber Mandala' },
    { id: 'penrose-tile', name: 'Penrose Tile' },
    { id: 'checker-wave', name: 'Checker Wave' },
    { id: 'hermann-grid', name: 'Hermann Grid' },
    { id: 'op-art', name: 'Op Art' },
    { id: 'stained-glass', name: 'Stained Glass' },
    { id: 'dot-halftone', name: 'Dot Halftone' },
    { id: 'wave-rings', name: 'Wave Rings' },
    { id: 'pendulum-wave', name: 'Pendulum Wave' },
  ]},
  { label: 'Organic', presets: [
    { id: 'cellular', name: 'Cellular' },
    { id: 'liquid', name: 'Liquid' },
    { id: 'voronoi', name: 'Voronoi' },
    { id: 'smoke', name: 'Smoke' },
    { id: 'oil-spill', name: 'Oil Spill' },
    { id: 'coral-reef', name: 'Coral Reef' },
    { id: 'flow-field', name: 'Flow Field' },
    { id: 'ant-colony', name: 'Ant Colony' },
    { id: 'bioluminescence', name: 'Bioluminescence' },
    { id: 'ink-blot', name: 'Ink Blot' },
    { id: 'ink-wash', name: 'Ink Wash' },
    { id: 'lava-lamp', name: 'Lava Lamp' },
    { id: 'lava-rise', name: 'Lava Rise' },
    { id: 'bubble-float', name: 'Bubble Float' },
    { id: 'growth-spiral', name: 'Growth Spiral' },
    { id: 'mycelium', name: 'Mycelium' },
    { id: 'fungal-web', name: 'Fungal Web' },
  ]},
  { label: 'Nature', presets: [
    { id: 'fractal-tree', name: 'Fractal Tree' },
    { id: 'flower-bloom', name: 'Flower Bloom' },
    { id: 'autumn-fall', name: 'Autumn Fall' },
    { id: 'dandelion-seeds', name: 'Dandelion Seeds' },
    { id: 'petal-storm', name: 'Petal Storm' },
    { id: 'meadow-breeze', name: 'Meadow Breeze' },
    { id: 'leaf-vein', name: 'Leaf Vein' },
    { id: 'vine-growth', name: 'Vine Growth' },
    { id: 'neon-vines', name: 'Neon Vines' },
    { id: 'forest-canopy', name: 'Forest Canopy' },
    { id: 'northern-forest', name: 'Northern Forest' },
    { id: 'seed-burst', name: 'Seed Burst' },
    { id: 'pollen-cloud', name: 'Pollen Cloud' },
    { id: 'tree-ring', name: 'Tree Ring' },
    { id: 'moss-carpet', name: 'Moss Carpet' },
    { id: 'lichen-spread', name: 'Lichen Spread' },
    { id: 'spore-drift', name: 'Spore Drift' },
  ]},
  { label: 'Water', presets: [
    { id: 'water-surface', name: 'Water Surface' },
    { id: 'river-stream', name: 'River Stream' },
    { id: 'waterfall-mist', name: 'Waterfall Mist' },
    { id: 'tide-wave', name: 'Tide Wave' },
    { id: 'tide-pool', name: 'Tide Pool' },
    { id: 'rain-puddles', name: 'Rain Puddles' },
    { id: 'pond-life', name: 'Pond Life' },
    { id: 'kelp-forest', name: 'Kelp Forest' },
    { id: 'ice-formation', name: 'Ice Formation' },
    { id: 'erosion-line', name: 'Erosion Line' },
  ]},
  { label: 'Grid & Tech', presets: [
    { id: 'glitch-grid', name: 'Glitch Grid' },
    { id: 'hexgrid-pulse', name: 'Hexgrid Pulse' },
    { id: 'grid-warp', name: 'Grid Warp' },
    { id: 'circuit-board', name: 'Circuit Board' },
    { id: 'crt-monitor', name: 'CRT Monitor' },
    { id: 'retro-terminal', name: 'Retro Terminal' },
    { id: 'circuit-trace', name: 'Circuit Trace' },
    { id: 'cyber-grid', name: 'Cyber Grid' },
    { id: 'hex-network', name: 'Hex Network' },
    { id: 'led-matrix', name: 'LED Matrix' },
    { id: 'dot-matrix', name: 'Dot Matrix' },
    { id: 'neural-net', name: 'Neural Net' },
    { id: 'isometric-city', name: 'Isometric City' },
    { id: 'wireframe-city', name: 'Wireframe City' },
    { id: 'floating-ui', name: 'Floating UI' },
    { id: 'data-stream', name: 'Data Stream' },
    { id: 'data-cascade', name: 'Data Cascade' },
    { id: 'data-sprites', name: 'Data Sprites' },
    { id: 'matrix-code', name: 'Matrix Code' },
    { id: 'matrix-rain', name: 'Matrix Rain' },
  ]},
  { label: 'Space', presets: [
    { id: 'starfield', name: 'Starfield' },
    { id: 'constellation', name: 'Constellation' },
    { id: 'bokeh', name: 'Bokeh' },
    { id: 'terrain', name: 'Terrain' },
    { id: 'meteor-shower', name: 'Meteor Shower' },
    { id: 'orbits', name: 'Orbits' },
    { id: 'cyber-sun', name: 'Cyber Sun' },
    { id: 'dna-helix', name: 'DNA Helix' },
    { id: 'crystal-lattice', name: 'Crystal Lattice' },
    { id: 'radar', name: 'Radar' },
    { id: 'sand-dunes', name: 'Sand Dunes' },
  ]},
  { label: 'Neon & Glow', presets: [
    { id: 'neon-80s', name: 'Neon 80s' },
    { id: 'neon-bars', name: 'Neon Bars' },
    { id: 'neon-dust', name: 'Neon Dust' },
    { id: 'neon-jellyfish', name: 'Neon Jellyfish' },
    { id: 'neon-smoke', name: 'Neon Smoke' },
    { id: 'electric-arc', name: 'Electric Arc' },
    { id: 'electric-city', name: 'Electric City' },
    { id: 'electric-fence', name: 'Electric Fence' },
    { id: 'lightning', name: 'Lightning' },
    { id: 'light-swarm', name: 'Light Swarm' },
    { id: 'fireflies', name: 'Fireflies' },
    { id: 'ember-drift', name: 'Ember Drift' },
    { id: 'cathode-glow', name: 'Cathode Glow' },
    { id: 'fire-wall', name: 'Fire Wall' },
    { id: 'paper-lantern', name: 'Paper Lantern' },
  ]},
  { label: 'Glitch & Retro', presets: [
    { id: 'glitch-8bit', name: 'Glitch 8bit' },
    { id: 'glitch-wave', name: 'Glitch Wave' },
    { id: 'cyber-glitch', name: 'Cyber Glitch' },
    { id: 'digital-noise', name: 'Digital Noise' },
    { id: 'static-burst', name: 'Static Burst' },
    { id: 'static-snow', name: 'Static Snow' },
    { id: 'radio-static', name: 'Radio Static' },
    { id: 'scramble-channel', name: 'Scramble Channel' },
    { id: 'flicker-strobe', name: 'Flicker Strobe' },
    { id: 'old-tv', name: 'Old TV' },
    { id: 'crt-scan', name: 'CRT Scan' },
    { id: 'retro-arcade', name: 'Retro Arcade' },
    { id: 'retro-wave', name: 'Retro Wave' },
    { id: 'arcade-blocks', name: 'Arcade Blocks' },
    { id: 'pixel-cascade', name: 'Pixel Cascade' },
    { id: 'pixel-mosaic', name: 'Pixel Mosaic' },
    { id: 'pixel-rain', name: 'Pixel Rain' },
    { id: 'pixel-sort-b', name: 'Pixel Sort' },
    { id: 'ascii-art', name: 'ASCII Art' },
  ]},
  { label: 'Audio Reactive', presets: [
    { id: 'frequency-rings', name: 'Frequency Rings' },
    { id: 'equalizer', name: 'Equalizer' },
    { id: 'sine-waves', name: 'Sine Waves' },
    { id: 'gradient-sweep', name: 'Gradient Sweep' },
    { id: 'wireframe-sphere', name: 'Wireframe Sphere' },
    { id: 'analog-wave', name: 'Analog Wave' },
    { id: 'audio-mesh', name: 'Audio Mesh' },
    { id: 'boombox-meter', name: 'Boombox Meter' },
    { id: 'dial-tone', name: 'Dial Tone' },
    { id: 'oscilloscope', name: 'Oscilloscope' },
    { id: 'pulse-ring', name: 'Pulse Ring' },
    { id: 'radial-burst', name: 'Radial Burst' },
    { id: 'synth-wave', name: 'Synth Wave' },
    { id: 'vinyl-groove', name: 'Vinyl Groove' },
    { id: 'cassette-reel', name: 'Cassette Reel' },
    { id: 'honeycomb-pulse', name: 'Honeycomb Pulse' },
  ]},
  { label: 'Particles', presets: [
    { id: 'snowfall', name: 'Snowfall' },
    { id: 'confetti-burst', name: 'Confetti Burst' },
    { id: 'particle-storm', name: 'Particle Storm' },
    { id: 'dust-motes', name: 'Dust Motes' },
    { id: 'bird-murmuration', name: 'Bird Murmuration' },
    { id: 'smoke-stack', name: 'Smoke Stack' },
    { id: 'fog-bank', name: 'Fog Bank' },
    { id: 'wind-ripple', name: 'Wind Ripple' },
  ]},
  { label: 'Weather', presets: [
    { id: 'rain', name: 'Rain' },
    { id: 'neon-rain', name: 'Neon Rain' },
    { id: 'cyber-rain-heavy', name: 'Cyber Rain' },
    { id: 'ceiling-drip', name: 'Ceiling Drip' },
  ]},
];

export const ALL_PRESETS = PRESET_CATEGORIES.flatMap(c => c.presets);
